### ISSUE TITLE
Send Hex doesn't work at all

### ISSUE THREAD

**Issue by paulhayes** [KangLin/SerialPortAssistant#1]
Steps:
1. Selecting Send Hex tickbox
2. typing: AA
3. Hit Send

Behaviour:
Dropped bytes counter increased by 2

Expected behaviour
Should send a single byte with value 0xAA
Tx Bytes counter increased by 1

**Comment by KangLin** [comment]
Thank you! Already modified, please test

**Comment by paulhayes** [comment]
Great! Can you publish a release build for 0.3.3? I don't have time to configure and build the project, but am happy to test your executable.

**Comment by KangLin** [comment]
It is upload in release. please test it.

**Comment by paulhayes** [comment]
Thanks @KangLin , I just tested this morning and it works. Thanks for the improvements, it's really appreciated. Keep up the great work!
