### ISSUE TITLE
可以加上控制信号的指示吗？

### ISSUE THREAD

**Issue by youxiaojie** [KangLin/SerialPortAssistant#10]
可以加上控制信号的指示吗？

**Comment by KangLin** [comment]
请详细描述，最好有图：）

**Comment by youxiaojie** [comment]
比如 cts rts ri 等五个控制信号

**Comment by KangLin** [comment]
已经增加 。请你从下面地址下载测试！

https://ci.appveyor.com/api/buildjobs/b9yo59b57b17nswj/artifacts/build_windows_msvc%2FSerialPortAssistant-Setup-v0.5.5.exe
