### ISSUE TITLE
neno 窗口不能拖动

### ISSUE THREAD

**Issue by scroot** [KangLin/SerialPortAssistant#13]
serialportassistant_0.5.9_Ubuntu-20.04_amd64.deb

运行环境：
neno  （ubuntu 20.04 + QT5 + wayland)
Linux kernel 5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

问题：
窗口位置不能拖动 （可以放大/缩小/关闭/改变窗口大小)

**Comment by KangLin** [comment]
已修复： 781d6f19e15210cbe6e3f5122d1c00e8f26920eb

**Comment by KangLin** [comment]
Please test v0.5.11
