### ISSUE TITLE
串口串口小一点

### ISSUE THREAD

**Issue by 652436962** [KangLin/SerialPortAssistant#17]
![image](https://github.com/KangLin/SerialPortAssistant/assets/34038936/f3454d73-3e13-4ff7-acde-fa42a6a0fc56)

类似这样
![image](https://github.com/KangLin/SerialPortAssistant/assets/34038936/fe7ad1d7-5955-4b47-82c6-a36e834e7d8a)

现在窗口放大直接占一半太大了

**Comment by KangLin** [comment]
已修改：https://github.com/KangLin/SerialPortAssistant/releases/tag/v0.5.18

![图片](https://github.com/KangLin/SerialPortAssistant/assets/8564669/f7f1a68b-3392-4dac-a8b1-6d1455a33321)
