### ISSUE TITLE
v0.5.16在红米K50ultra上无法安装

### ISSUE THREAD

**Issue by kkkdxy** [KangLin/SerialPortAssistant#19]
![54b43c16c95e4c932fac8902ae973f3](https://github.com/KangLin/SerialPortAssistant/assets/13811367/f6a5f42c-6f61-4cfd-a2f0-73c3335a3039)
![39a1e6d4828f67f824de07ece027285](https://github.com/KangLin/SerialPortAssistant/assets/13811367/f2f1a900-a994-4d9b-8a3e-39cf7a5d8c8f)
安装如图所示，最新只能安装到v0.5.9

**Comment by KangLin** [comment]
有可能是以下几种情况：
- 你下载的包没下完整。请确认包的 MD5 值是否一样。
- 签名的问题。你先把以前安装的包完全删除。然后再装新包。
- 芯片架构不匹配。请把你的芯片架构发出来。

**Comment by KangLin** [comment]
我先关了。如果还有问题，再重新打开此PR。
