### ISSUE TITLE
无法识别串口

### ISSUE THREAD

**Issue by gjk0510** [KangLin/SerialPortAssistant#20]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KangLin** [comment]
请列出以上详细信息

**Comment by KangLin** [comment]
如果你的串口是非标准命名，你可以手动输入串口。

**Comment by KangLin** [comment]
如果你的串口是非标准命名，你可以手动输入串口。
