### ISSUE TITLE
Deb package for 22.05 QT5 based 

### ISSUE THREAD

**Issue by alphafox02** [KangLin/SerialPortAssistant#22]
You’re application is working great as I need RTS I think it’s called capability, however on 22.04 it requires about 200 meg of additional QT6 related packages as well as a package (in my case) that’s not pulled in with apt-get -f.

You seem to need the following in order for the gui to load otherwise you’ll get a failure,
qt6-qpa-plugins

My request is to see if your application (deb release) can be built for qt5?

**Comment by alphafox02** [comment]
I had no issues building from source on 22.04 against the QT5 packages. It would be great if there was an official release for QT5/22.04.

**Comment by KangLin** [comment]
This is because Qt no longer supports Qt5. So the release version uses Qt6. You can compile Qt5 packages from source
with build_debpackage.sh

**Comment by KangLin** [comment]
> You’re application is working great as I need RTS I think it’s called capability, however on 22.04 it requires about 200 meg of additional QT6 related packages as well as a package (in my case) that’s not pulled in with apt-get -f.

ubuntu 22.04 shouldn't require `apt-get -f`

**Comment by alphafox02** [comment]
For whatever reason it did for me, but then I also had to install that plugin I mentioned. That was using your release version. When I compiled it myself for qt5 using the deb builder script - I did not have to use the -f but I also happen to already have all the dependencies. I’ll close this ticket out and continue to test. Working great for what I need so far! Thank you.
