### ISSUE TITLE
Please add "Refresh Ports" function

### ISSUE THREAD

**Issue by probonopd** [KangLin/SerialPortAssistant#3]
Please add "Refresh Ports" function. When I have _first_ opened the SerialPortAssistant, and _then_ plugin in a USB-to-serial adapter, it is _not_ shown in the menu.

Adding such a button would help:

![](https://user-images.githubusercontent.com/2480569/60766624-cc54df00-a09b-11e9-8ba3-144200a82a57.png)

Code:
https://github.com/sakisds/CuteESP/blob/baf4a50ec13e0a0fa36323a0bca6d22504701717/src/MainWindow.cpp#L102-L115

Or is there a way to make it work without having to press a button?

**Comment by KangLin** [comment]
OK, I has add the function in v0.4.3. please test it.

**Comment by probonopd** [comment]
Unfortunately I can't seem to find a new AppImage?

**Comment by KangLin** [comment]
I has modify pro file. CI has a bug, so there isn't AppImage. But you can compile it.

**Comment by KangLin** [comment]
FIX ci bug In v0.4.4 . please test it. thanks!

**Comment by KangLin** [comment]
The Release v0.4.8 is used. please test it.

**Comment by probonopd** [comment]
Thank you very much.
