### ISSUE TITLE
Underline characters in menu without ()

### ISSUE THREAD

**Issue by probonopd** [KangLin/SerialPortAssistant#5]
Underline characters in menu without ()

Example:

![](https://user-images.githubusercontent.com/2480569/60766816-92d1a300-a09e-11e9-9f76-1a57aa07c347.png)

Top: Not correct :-1: 
Bottom: Correct :+1:

**Comment by KangLin** [comment]
The software I have seen is my practice, your method I first saw.

**Comment by probonopd** [comment]
It is common at least on Linux. I have not checked Windows. Thanks for your consideration.
