### ISSUE TITLE
libRabbitCommon.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by probonopd** [KangLin/SerialPortAssistant#6]
Missing libRabbitCommon.so.0, cannot run.

**Comment by probonopd** [comment]
linuxdeployqt should bundle these things - why did you comment out linuxdeployqt?

**Comment by KangLin** [comment]
Do you forget add the directory of libRabbitCommon.so.0 add to LD_LIBRARY_PATH?

**Comment by KangLin** [comment]
Add the directory of  libRabbitCommon.so.0 add to LD_LIBRARY_PATH, can build AppImage. See: https://travis-ci.org/KangLin/SerialPortAssistant/jobs/566277378

Error information:

l@l-Lenovo:/opt/SerialPortAssistant$ ./SerialPort_Assistant-v0.4.5-x86_64.AppImage 
./SerialPort_Assistant-v0.4.5-x86_64.AppImage: symbol lookup error: ./SerialPort_Assistant-v0.4.5-x86_64.AppImage: undefined symbol: _ZN12RabbitCommon6CTools4InitE7QString

**Comment by probonopd** [comment]
I am using:

```
me@host:~$ wget https://github.com/KangLin/SerialPortAssistant/releases/download/v0.4.5/SerialPortAssistant_v0.4.5.tar.gz
(...)

2019-08-01 20:31:01 (4.45 MB/s) - ‘SerialPortAssistant_v0.4.5.tar.gz’ saved [39148454/39148454]

me@host:~$ tar xfvz SerialPortAssistant_v0.4.5.tar.gz 

me@host:~$ ./SerialPortAssistant-x86_64.AppImage 
./SerialPortAssistant-x86_64.AppImage: error while loading shared libraries: libRabbitCommon.so.0: cannot open shared object file: No such file or directory
```

**Comment by KangLin** [comment]
Yes, This seems to be an incorrect AppImage setting. I don't know configure it in AppImage. I want to view AppImage content, but I am getting an error mounting it.

l@l-Lenovo:/opt/SerialPortAssistant$ sudo mount -o loop SerialPort_Assistant-v0.4.5-x86_64.AppImage /tmp/serial/
NTFS signature is missing.
Failed to mount '/dev/loop20': Invalid argument
The device '/dev/loop20' doesn't seem to have a valid NTFS.
Maybe the wrong device is used? Or the whole disk instead of a
partition (e.g. /dev/sda, not /dev/sda1)? Or the other way around?

**Comment by probonopd** [comment]
`./SerialPort_Assistant-v0.4.5-x86_64.AppImage --appimage-extract`

**Comment by probonopd** [comment]
Or `./SerialPort_Assistant-v0.4.5-x86_64.AppImage --appimage-mount`

**Comment by KangLin** [comment]
There are libRabbitCommon.so.0 in AppImage. So Is it a bug in linuxdeployqt?

l@l-Lenovo:/opt/SerialPortAssistant/squashfs-root/SerialPortAssistant/bin$ ls
libRabbitCommon.prl   libRabbitCommon.so.0.4    SerialPortAssistant
libRabbitCommon.so    libRabbitCommon.so.0.4.5
libRabbitCommon.so.0  qt.conf

**Comment by probonopd** [comment]
>So Is it a bug in linuxdeployqt?

Maybe, maybe not. I am going to try https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci to see if it works then.

**Comment by KangLin** [comment]
I am checked ci. The SerialPort_Assistant-v0.4.8-x86_64.AppImage is run in CI. 
See: https://travis-ci.org/KangLin/SerialPortAssistant/jobs/569219639
        LINE: 997-1021

The code :  https://github.com/KangLin/SerialPortAssistant/blob/65f29f7493f716b014b9bebdf6557f6be2c5544e/ci/build.sh#L127-L130

I think to setting LD_LIBRARY_PATH in CI environment.

But after downloading, it can't be run locally, there is a error cannot open shared object file

The application is install to **/opt/SerialPortAssistant** directory.

**Comment by KangLin** [comment]
I already know the cause of the error.

In the CI environment, I am installed the program to: /home/travis/build/KangLin/SerialPortAssistant/debian/serialportassistant/opt/SerialPortAssistant/ 

libRabbitCommon.so is installed at /home/travis/build/KangLin/SerialPortAssistant/debian/serialportassistant/opt/SerialPortAssistant/bin

linuxdeployqt does not correctly identify path of the libRabbitCommon.so and install it into the lib directory.

If I am installed the program to /opt/SerialPortAssistant , then the linuxdeployqt can correctly identif path of the libRabbitCommon.so and install it into the lib directory.

So. please you are review linuxdeployqt source code.

**Comment by probonopd** [comment]
Please `export LD_LIBRARY_PATH=...` before calling `linuxdeployqt ` so that it can find `libRabbitCommon.so`.

**Comment by KangLin** [comment]
I used export  LD_LIBRARY_PATH=... before calling linuxdeployqt. But it is the cause of this error.
Because the libRabbitCommon.so in the bin directory, not in the lib directory.

**Comment by probonopd** [comment]
Can you have it outside of the appdir before calling `linuxeployqt`? `linuxdeployqt` will find it using `ldd` and copy it into the correct place in the appdir automatically. It should not be in the appdir before calling `linuxdeployqt`. But `ldd` needs to be able to find it.
