### ISSUE TITLE
请问arm环境下怎么配置

### ISSUE THREAD

**Issue by yicong1352013** [KangLin/SerialPortAssistant#8]
我使用QT编译运行没问题，但是直接运行生成的文件报错误
`pi@raspberrypi:~/seastone/build-SerialPortAssistant-unknown-Release/bin $ ls -lh

总用量 1.1M

-rw-r--r-- 1 pi pi  509 7月  31 10:05 libRabbitCommon.prl

lrwxrwxrwx 1 pi pi   24 7月  31 10:09 libRabbitCommon.so -> libRabbitCommon.so.1.0.0

lrwxrwxrwx 1 pi pi   24 7月  31 10:09 libRabbitCommon.so.1 -> libRabbitCommon.so.1.0.0

lrwxrwxrwx 1 pi pi   24 7月  31 10:09 libRabbitCommon.so.1.0 -> libRabbitCommon.so.1.0.0

-rwxr-xr-x 1 pi pi 336K 7月  31 10:09 libRabbitCommon.so.1.0.0

-rwxr-xr-x 1 pi pi 728K 7月  31 10:09 SerialPortAssistant

`

`pi@raspberrypi:~/seastone/build-SerialPortAssistant-unknown-Release/bin $ ./SerialPortAssistant 

./SerialPortAssistant: error while loading shared libraries: libRabbitCommon.so.1: cannot open shared object file: No such file or directory
`

**Comment by KangLin** [comment]
请详细描述环境，系统

**Comment by KangLin** [comment]
1. 设置 LD_LIBRARY_PATH 。设置  libRabbitCommon.so.1.0.0 目录到 LD_LIBRARY_PATH 
  
或者：

2. 用 ldconfig 命令加载动态库.

**Comment by KangLin** [comment]
详见： #6
